apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-env
  labels:
    name: sample-secret-env
spec:
  containers:
  - name: sample-secret-env
    image: nginx:1.16
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"
        
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: sample-db-auth
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sample-db-auth
          key: password