apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  hostNetwork: true
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: nginx-container-113
    image: redis:3.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"



