import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { AppTemplate } from '../components/templates/AppTemplate';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <AppTemplate />
    </main>
  </div>
);

export default Home;
